<MyList>:
    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height

        GridLayout:
            cols: 6

            Label:
                text: "Id"
            Label:
                text: "Nombre"
            Label:
                text: "Temporada"
            Label:
                text: "Capítulos"
            Label:
                text: "Emitido"
            Label:
                text: "Siguiente capítulo"
            
            

